language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=34

matrix:
  finish_fast: true
  include:
    - php: 7.1
      env: COMPOSER_CMD=install
    - php: hhvm
      dist: trusty

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install: if [ "$COMPOSER_CMD" = "install" ]; then composer install --prefer-dist; else composer update --prefer-dist; fi

before_script:
  - bin/console doctrine:phpcr:init:dbal --force -e=test
  - bin/console doctrine:phpcr:repository:init -e=test

script: make test

notifications:
  irc: "irc.freenode.org#symfony-cmf"
